.gitignore

다음 파일들이 Git 저장소에 포함되지 않도록 설정합니다.
- Terraform 디렉터리 및 상태 파일(.terraform/, *.tfstate 등)
- QueryPie 라이선스 파일(.license.crt)
- QueryPie Docker 레지스트리 자격 증명(.docker-config.json)
- QueryPie Terraform 설정 파일(.querypie.tfvars)
- AWS 개인 키 파일(*.pem)

QueryPie Terraform 설치를 위한 .gitignore 추가

---

cs-reporter/querypie_cs_report.sh

- QueryPie 컨테이너 자동 감지 시 `querypie-app`으로 시작하는 컨테이너를 우선적으로 선택하도록 필터 수정. (기존: `name=^querypie` -> 변경: `name=^querypie-app`) 이를 통해 인자 없이 스크립트 실행 시 `querypie-redis` 등 다른 서비스 컨테이너가 잘못 선택되는 문제 해결.
- 컨테이너 내부 네트워크 정보 수집 시 `docker exec` 명령어에서 하드코딩된 'querypie' 대신 `$QUERYPIE_NAME` 변수를 사용하도록 수정.

Fix: QueryPie 컨테이너 자동 감지 로직 개선 및 변수 사용 오류 수정

---

aws-ami/scripts/setup.v2.sh

- setup.v2.sh 를 실행할 때, 설치 명령, 버전을 argument 로 넘겨 받는 방식으로, 실행 방식을 변경합니다.
- 환경변수에서 대상을 입력받는 방식은, 이후 필요에 따라 구현할 예정입니다.
- 현재 구현 중인 기능은 --install-partially-for-ami 입니다.
- 사용법
```
Usage: setup.v2.sh [options] <version>
or setup.v2.sh [options] --install <version>
or setup.v2.sh [options] --install-partially-for-ami <version>
or setup.v2.sh [options] --upgrade <version>
or setup.v2.sh [options] --resume
or setup.v2.sh [options] --populate-env <compose-env-file>
or setup.v2.sh [options] --help
OPTIONS:
-x, --xtrace        Print commands and their arguments as they are executed.
-h, --help          Show this help message.
```
- Local macbook 에서 기능 작동을 검증하였습니다.

AMI 빌드 - setup.v2.sh 실행 방식 변경

---

aws-ami/querypie-ami.pkr.hcl
aws-ami/scripts/setup.v2.sh

- setup.v2.sh --install-partially-for-ami 기능을 추가로 보완합니다.
- setup.v2.sh --resume 기능을 구현합니다.
- 기존 Packer script 의 설치 과정을, setup.v2.sh 의 구현으로 대체합니다.
- AMI 빌드에 성공합니다.
- 빌드된 AMI 로, EC2 VM 생성하고, QueryPie 가 곧바로 실행되는 것을 확인하였습니다.

AMI 빌드 - setup.v2.sh --resume 을 구현

---

aws-ami/ami-build.sh
aws-ami/ami-ls.sh
aws-ami/querypie-ami.pkr.hcl
aws-ami/scripts/setup.v2.sh

- Refactor setup.v2.sh
- Input validation 은 `function main()` 에서 수행하도록 변경합니다.
- Command 등 기능을 수행하는 함수에서는, input 값의 유효성을 검사하지 않아도 됩니다.
- 이를 통해, Input validation 코드를 더 간결하게 줄입니다.
- `ami-build.sh`
- 기존 `build-ami.sh` 의 이름을 바꾸어, `ami-build.sh` 로 변경합니다. `ami-` 로 시작하는 스크립트들과 나란히 목록에 나타나도록 이름을 바꿉니다.
- AMI 의 이름을, `ami-build.sh` 에서 결정합니다. Packer script 내부에서, 문자열을 조합하여 결정하지 않고, Caller 에서 결정하기에, AMI 이름을 따로 알아내지 않아도 됩니다.
- 빌드 직후, `ami-build.sh`에서 생성된 AMI ID 를 알아내도록, 개선합니다.
- `ami-ls.sh` 도입
- AWS 계정에 생성된 AMI 전체를 테이블 형식으로 조회합니다.
- AMI 빌드에 성공합니다.

AMI 빌드 - Refactor setup.v2.sh, packer script

---

podman/README.md
podman/database-compose.yml

- 하나의 docker-compose.yml 대신, database.yml, querypie.yml, tools.yml 등 Compose Yaml 을 세 개로 분리합니다. 
- MySQL 데이터 경로를 Container Volume 으로 제공합니다.
- 디렉토리 경로를 Mount 하는 경우, chown 을 수행하지 못한다는 오류가 발생합니다.
- 그 외 변경사항에 대해, README.md 의 설명을 참조하여 주세요.
docker-compose 로 실행하기 - 초기 DB 생성, PASSWORD 적용 확인
```
[ec2-user@ip-172-31-11-201 podman]$ docker-compose -f database-compose.yml up -d
[+] Running 4/4
⠿ Container querypie-redis-1    Started    0.5s
⠿ Container querypie-mysql-1    Started   0.6s
[ec2-user@ip-172-31-11-201 podman]$ cat ~/.my.cnf
[client]
host=127.0.0.1
database=querypie
user=querypie
password=<password>
[ec2-user@ip-172-31-11-201 podman]$ mysql -e "SHOW DATABASES;"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| performance_schema |
| querypie …
```

Podman: MySQL, Redis 를 위한 database.yml 을 구현합니다.

---

aws-ami/scripts/setup.v2.sh

- querypie/querypie:tag 라는 image repository:tag 에는 docker.io 라는 registry 가 명시되어 있지 않습니다.
- podman 환경 등을 고려하여, docker-compose.yml 의 image repository 에서, docker registry 를 docker.io 라고 명시합니다.

setup.v2.sh: docker registry 명시하기

---

aws-ami/scripts/setup.v2.sh

- SCRIPT_VERSION="25.07.5"
- `./querypie/` 디렉토리만 존재하고, current symbolic link 가 없는 경우, 에러와 함께 설치를 중단하는 기존 작동방식을 변경하여, 새로운 설치를 진행합니다.
- QPD-3079 에서 보고된 설치 중단 현상을 해결합니다.
- 정상적으로 설치됩니다.

setup.v2.sh: Fix cmd::install_recommended

---

aws-ami/scripts/setup.v2.sh

- macos 에서 제공되는 bash 3, zsh 5.x 와 호환되는 코드를 작성합니다.
- zsh compatibility
- bash 의 `${!name}` 기능, indirect expansion 에 대응하는 `${(P}name}` indirect expansion 을 적용합니다.
- `read -p <prompt>` 를 zsh 에서 지원하지 않습니다. 이에 대응합니다.
- regular expression matching 구현 방식이 bash 와 다릅니다.
- bash 3 compatibility
- empty array 인 arguments 를 `set -- "${arguments[@]}"` 하지 못합니다.
- macos bash 3 를 이용해 설치 가능합니다. 다만, tools 실행에 오류가 발생하여, 다음 단계로 진행하지 못합니다.
- `/bin/bash setup.v2.sh` 로 실행
- macos zsh 5.9 를 이용해 설치 가능합니다. 다만, tools 실행에 오류가 발생하여, 다음 단계로 진행하지 못합니다.
- `zsh setup.v2.sh` 로 실행

setup.v2.sh: Improved Compatibility with zsh, bash 3

---

podman/README.md
podman/podman-compose.yml

- 기존에는 database-compose.yml, tools-compose.yml, querypie-compose.yml 등 3개 compose.yml 을 제공하였습니다.
- 이 변경에서는 podman-compose.yml 하나의 compose.yml 로 기존 3개 설정파일을 대체하는 기능을 제공합니다.
- name 을 `querypie` 로 둡니다.
- container_name 을 명시하지 않습니다.
- podman-compose 를 위한 필수 변경 사항이 적용되어 있고, docker-compose 와 호환됩니다.
- README.md 를 podman-compose.yml 파일 기준으로 수정합니다.
- podman-compose 를 이용해 설치가 잘 됩니다.

podman: podman-compose.yml 설정 구현

---

aws-ami/az2023-install.pkr.hcl
aws-ami/ubuntu24.04-install.pkr.hcl
aws-ami/ubuntu24.04-install.sh

- Amazon Linux 2023 의 설정파일을 수정없이 복사하여, ubuntu24.04-install.sh, ubuntu24.04-install.pkr.hcl 파일을 만듭니다.
- 이후 Ubuntu 24.04 에 맞추어 최소한의 변경을 적용합니다.
- docker 설치 후, ssh session 을 끊습니다.
- `provisioner` 마다 개별적으로 ssh session 이 생성되지 않습니다. bash script 내부에서 실행되기에, logout 으로 ssh session 을 종료할 수 없습니다.
- 이에 따라, sshd process 를 강제로 종료합니다.
- Use `[` instead of `[[` for more compatibility.`
- Root block device 의 이름을 정확히 알아내고, 이를 launch_block_device_mappings 에 적용합니다.
- Root block device 의 이름을 정확히 지정하지 않으면, 새로운 block device 가 추가됩니다.
- 기존 Root block device 의 설정값이 변경되지 않아, 기본값 8 GiB 의 작은 volume 이 만들어집니다.
- `provisioner "shell"` 블럭에서, inline_shebang 을 설정하고, `set -o xtrace` 명령을 제거합니다.
- inline_shebang 은 `/bin/sh` 또는 `dash`가 실행되지 않고, `/bin/bash`가 실행되도록, 경로를 명시합니다.
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % …
```

AMI: Ubuntu 24.04 x86_64 에서 설치 기능 검증을 자동화합니다.

---

aws-ami/install.sh
aws-ami/scripts/install-docker-on-ubuntu.sh
aws-ami/ubuntu22.04-install.pkr.hcl
aws-ami/ubuntu24.04-install.pkr.hcl

- 설치 테스트 대상이 되는 리눅스 배포본의 수가 늘어나고 있습니다. 이에 따라, Packer 스크립트 실행을 위한 wrapper shell script 를 공통으로 구현합니다: `install.sh`
- Ubuntu 에서 Docker 를 설치하는 스크립트, `install-docker-on-ubuntu.sh`를 22.04, 24.04 모두에 작동하도록 구현합니다.
- ubuntu22.04-install.pkr.hcl 를 구현합니다.
- az2023-install.pkr.hcl 에서 docker 설치를 제거합니다. 이미 docker 가 설치되어 있습니다.
- `./install.sh az2023 11.0.1` 성공
- `./install.sh ubuntu24.04 11.0.1` 성공
- `./install.sh ubuntu22.04 11.0.1` 실패 - tools 실행시 비밀번호 오류. TODO(JK): 추후 해결

AMI: ubuntu-22.04 amd64 에서 설치 테스트 수행

---

aws-ami/scripts/setup.v2.sh

- mysqld container 실행 대기시간을 10초에서 20초로 늘입니다. tools 실행 실패의 가능성을 줄입니다.
- SCRIPT_VERSION="25.08.1"

setup.v2.sh: mysqld 대기시간 조정

---

aws/scripts/setup.v2.sh

- SCRIPT_VERSION="25.08.2"
- RECOMMENDED_VERSION="11.1.1"
- 설치 버전을 11.0.1 에서 11.1.1 로 업데이트합니다. 11.1.1 은 amd64, arm64 모두를 지원합니다.
- `setup.v2.sh --uninstall` 명령을 구현합니다.
- container 를 먼저 종료합니다.
- mysql data 를 삭제합니다.
- ./querypie/current 가 가리키는 ./querypie/<version>/ 을 삭제합니다.
```
[ec2-user@ip-172-31-11-201 ~]$ ./setup.v2.sh --uninstall
+ docker stop querypie-app-1
querypie-app-1
+ docker rm querypie-app-1
querypie-app-1
+ docker stop querypie-redis-1
querypie-redis-1
+ docker rm querypie-redis-1
querypie-redis-1
+ docker stop querypie-mysql-1
querypie-mysql-1
+ docker rm querypie-mysql-1
querypie-mysql-1
+ sudo rm -rf ./querypie/mysql
+ rm -rf ./querypie/11.1.1
+ rm -f ./querypie/current
[ec2-user@ip-172-31-11-201 ~]$ ./setup.v2.sh --uninstall
[ec2-user@ip-172-31-11-201 ~]$ 
```

setup.v2.sh: uninstall 구현

---

aws/scripts/install-docker-on-rhel8.sh
aws/verify-install/rhel8.pkr.hcl

- aws/scripts/install-docker-on-rhel8.sh 를 구현합니다.
- `killall sshd` 대신 `pkill -f sshd`을 사용하여야, sshd process 가 종료됩니다.
- rhel8.pkr.hcl 를 작성합니다.
- Spot Instance Price 를 다른 경우보다 높게 설정합니다. Software 가격이 포함되어 있기 때문입니다. Fix install-docker-on-rhel8.sh
- 설치 과정에서, SELinux 설정 변경이 필요합니다.
`./verify-install.sh 11.1.1 rhel8 x86_64` - 성공
`./verify-install.sh 11.1.1 rhel8 arm64` - 성공
```
2025-08-21T15:32:49+09:00: #
2025-08-21T15:32:49+09:00: ## Verify SELinux settings
2025-08-21T15:32:49+09:00: #
2025-08-21T15:32:49+09:00: # SELinux is installed on this system.
2025-08-21T15:32:49+09:00: # SELinux is enabled on this system.
2025-08-21T15:32:49+09:00: # The current mode of SELinux is enforcing.
2025-08-21T15:32:49+09:00: ## You may need to change the SELinux context of the ./querypie directory. …
```

AWS: RHEL8 설치 검증 자동화

---

aws/scripts/setup.v2.sh
compose/local-reset.sh

- SCRIPT_VERSION="25.08.4"
- 기존 Docker Compose 사용방식은, `/usr/local/bin/docker-compose` 명령을 직접 호출하였습니다.
- 변경된 방식은, `docker compose` 방식으로 Compose Tool 을 Docker Plugin 형태로 사용합니다. 더이상 `docker-compose` 실행파일을 직접 실행하지 않습니다.
- 이에 따라, setup.v2.sh 의 몇몇 함수를 재작성합니다.
- `verify::docker_installation` 함수를 `verify::container_engine_installation` 로 이름을 바꾸고 수정합니다.
- `install::docker_compose` 함수를 재작성합니다. 특히, docker-compose 실행파일을 `~/.docker/cli-plugins/docker-compose` 에 설치합니다.
- `command_exists` 함수를 `command::whereis` 로 재작성합니다.
- `~/.docker/cli-plugins/docker-compose`에 설치된 Compose Tool 은 Podman 에서도 `podman compose` 라고 호출하여 곧바로 사용할 수 있습니다.
- 이에 따라, 이용자에게 `podman-compose`를 미리 설치할 것을 요구하지 않습니다. `podman` 은 `dnf` 명령으로 쉽게 설치가 되지만, `podman-compose` 는 pip 로 설치해야 하기에, python3 upgrade, pip repository 접근 등 의존성이 크게 요구됩니다. …

setup.v2.sh: Docker Compose 를 Docker Plugin 으로 사용합니다

---

aws/scripts/setup.v2.sh
aws/verify-install/amazon-linux-2023.pkr.hcl
aws/verify-install/rhel8.pkr.hcl

- setup.v2.sh 는 RHEL8 에서 Docker 대신 Podman 을 기본 설치하도록 변경합니다.
- 이후, Rootless Mode, Podman 운영 환경을 검증하는데 활용합니다.
- `./verify-install.sh 11.1.1 rhel8 x86_64 none`: 성공
- 다음은 RHEL8 에서 Podman 설치 때, 함께 설치되는 패키지의 내역, 상세한 설치 과정입니다.
```
2025-08-22T15:16:49+09:00: + sudo dnf -y -q --best install podman podman-plugins podman-manpages
2025-08-22T15:18:43+09:00:
2025-08-22T15:18:43+09:00: Installed:
2025-08-22T15:18:43+09:00:   conmon-3:2.1.10-1.module+el8.10.0+23320+f7205097.x86_64
2025-08-22T15:18:43+09:00:   container-selinux-2:2.229.0-2.module+el8.10.0+23320+f7205097.noarch
2025-08-22T15:18:43+09:00:   containernetworking-plugins-1:1.4.0-6.module+el8.10.0+23320+f7205097.x86_64
2025-08-22T15:18:43+09:00:   containers-common-2:1-82.module+el8.10.0+23320+f7205097.x86_64
2025-08-22T15:18:43+09:00: …
```

setup.v2.sh: RHEL8 에서 Podman 을 기본 설치합니다.

---

aws/ami/ami-ls.sh
aws/ec2

- Terminate 대상을 보여주고, yes 입력을 받아 삭제합니다.
- 목록 보여주기 화면을 개선합니다.
```
% ./ec2
EC2 Instance Management Script v25.08.2
Usage:
./ec2 start     - Start all instances owned by jk
./ec2 stop      - Stop all instances owned by jk
./ec2 terminate - Terminate instances owned by jk (per-instance confirmation)
./ec2 status    - List instances owned by jk
./ec2 help      - Show this help message
Note: This script automatically finds and manages all EC2 instances
tagged with Owner=jk (case-insensitive matching)
```
- owner, name 을 입력받아, 해당하는 AMI 목록을 조회할 수 있습니다.
```
% ./ami-ls.sh --help
Usage: ./ami-ls.sh [self|marketplace|redhat|rocky|canonical] [name]
EXAMPLES:
./ami-ls.sh self querypie
./ami-ls.sh rocky Rocky-8-
%
```

AWS: ec2 도구와 ami-ls.sh 를 개선합니다.

---

compose/universal/README.ja.md
compose/universal/README.ko.md
compose/universal/README.md
compose/universal/compose.yml

- Podman Compose 대신, Podman + Docker Compose 조합으로 사용하는 권장합니다.
- `setup.v2.sh`에서 Podman 을 자동으로 설치하기에, Podman, Podman Compose 설치 방법을 별도로 안내하지 않습니다.
- `compose.yml` 에서 mysql data dir 의 경로를 변경합니다.
- `./mysql`이 아닌 `../mysql`을 사용하도록, 변경합니다. 이에 따라, `setup.sh`를 이용하여 Universal Compose Package 를 설치하더라도, `../mysql` 경로를 mysql data dir 로 사용하게 됩니다.
- README.ko.md 를 원본으로 문서를 작성하고, README.md, README.ja.md 를 기계 번역합니다.

Compose: Universal Compose Package 를 개선합니다.

---

aws/ami/ami-ls.sh
aws/scripts/setup.v2.sh
aws/verify-install/centos9.pkr.hcl

- setup.v2.sh Container Engine 을 설치할 때, Podman 을 기본 설치합니다.
- CentOS Stream 9 에서 제공되는 /etc/os-release 의 변수값을 확인합니다.
- ID=centos 의 경우, Podman 을 기본 설치하도록 설정합니다.
- 설치 검증 자동화를 위해, centos9.pkr.hcl 파일을 작성합니다. CentOS Stream 9 을 설치합니다.
- CentOS 8 또는 CentOS Stream 8 은 더이상 AWS Marketplace 에서 제공되지 않습니다.
- us-west-2 region 에서 제공되는 AMI 가 있기는 하나, ap-northeast-2 에서는 제공되지 않습니다.
- CentOS 8 은 AWS Marketplace 에서 Officially 제공되지 않는 것으로 간주합니다.
- ami-ls.sh 를 개선합니다.
- AMI 생성일 최신순으로 정렬합니다.
- CentOS 를 제공하는 AWS Marketplace 의 Cloud Platform Engineering (CPE) 계정은 125523088429 라고 알려져 있습니다. 출처: ChatGPT
- `./verify-install.sh 11.1.1 centos9 arm64 none`: 성공
- `./verify-install.sh 11.1.1 centos9 x86_64 none`: 성공

setup.v2.sh: CentOS Stream 9 에서 Podman 을 기본 설치합니다.

---

aws/scripts/install-podman-on-rhel8.sh
aws/scripts/setup.v2.sh

- SCRIPT_VERSION="25.08.5"
- setup.v2.sh 는 RHEL 계열의 배포본에서 Podman 을 기본 설치하도록, 기능을 변경하였습니다.
- 이때, `podman-docker` 패키지를 함께 설치하여, `docker`와 동일한 명령어로 실행/운영할 수 있도록, 설치 환경을 구성합니다.
- 이용자에게, Docker 대신 Podman 을 기본 설치한다고 안내하더라도, 실제 사용하는 명령어는 Docker 와 동일한 경험을 제공합니다.
- 앞으로도, Podman 설치시, podman-docker 패키지를 함께 설치하는 것을 관습으로 유지합니다.
- 이용자가 Podman 을 별도로 사전 설치하는 경우, `podman-docker` 패키지를 필수로 요구하지 않습니다. `podman` 명령이 발견되는 경우, `podman`으로 컨테이너를 관리합니다.

setup.v2.sh: Podman 설치 때, podman-docker 패키지를 함께 설치합니다.

---

compose/offline-package.sh
compose/offline/.gitignore

- `offline-package.sh` 의 기능을 개선하여, Container Image 저장 기능을 추가합니다.
- `compose.yml` 파일의 경로를 입력받습니다, `docker compose config` 명령을 활용하여, container image 이름을 알아냅니다. 이 image 의 내역을 `offline/images.txt` 에 저장합니다.
- image 를 적당한 파일이름으로 바꾸어, `docker save`로 내보내기 수행합니다.
- 사용법
```
% ./offline-package.sh
Usage: ./offline-package.sh <compose.yml> <version> [platform]
compose.yml: Path to the docker-compose YAML file
version: QueryPie version to save as .tar (e.g., 11.1.2)
platform: Target platform for the container images (e.g., linux/amd64 or linux/arm64)
EXAMPLES:
./offline-package.sh universal/compose.yml 11.1.2 linux/amd64
./offline-package.sh universal/compose.yml 11.1.2 linux/arm64
```
- `./offline-package.sh universal/compose.yml 11.1.2`: 성공
```
% ls -al offline
total 10254568
drwxr-xr-x  11 jk …
```

offline-package.sh: Container Image 저장 기능 구현

---

aws/ami/ami-build.sh
aws/ami/ami-ls.sh
aws/ami/ami-verify.sh
aws/ec2
aws/scripts/setup.v2.sh
aws/verify-install/verify-install.sh
aws/verify-upgrade-uninstall/verify-upgrade-uninstall.sh
compose/offline-package.sh

- 여러 bash script 에 사용되는 `log::do` 함수를 개선합니다.
- Ctrl-C 입력하여 Interrupt 하는 경우, bash script 가 실행을 중단하도록, 개선합니다.
- 오류가 발생한 bash script line number 를 에러메시지에 노출합니다.
- `if "$@"; then return 0; else return 1; fi` 방식의 코드는 오류 발생시 bash 의 행동을 바꾸게 됩니다.
- Ctrl-C 입력에 따른 Interrupt 의 경우, `log::do command`의 실행이 중단되지 않고, 계속 실행되는 현상이 발생할 수 있습니다.
- `while read -r variable;` loop 내에서 ` log::do command` 로 실행 중인 명령을 Ctrl-C 로 중단하는 경우, script 실행이 멈추지 않고 계속 진행됩니다.
- `push-to-private-registry.sh` 스크립트 구현 과정에서 이러한 문제가 발견되었습니다.

Fix: bash script 의 log::do 를 개선합니다.

---

aws/scripts/setup.v2.sh
compose/offline-package.sh

- OFFLINE_DIR 의 기본값은 `./offline/`입니다.
- setup.v2.sh 에서 `install::load_image_from_tarball_in_offline`을 구현합니다.
- OFFLINE_DIR 에 `images.txt`가 존재하는 경우, 이 파일을 읽어, container image 를 로딩합니다.
- setup.v2.sh 에서, 신규 설치 `cmd::install`,  업그레이드 `cmd::upgrade`, 두 가지 명령 수행시, Compose Package 압축 해제 직후, `install::load_image_from_tarball_in_offline` 를 수행합니다.
- `install::load_image_from_tarball_in_offline` 에서 container image 가 로딩된 경우, docker compose pull 을 생략하고 실행하지 않습니다.
- offline-package.sh 개선사항
- `novac` 이미지를 save 합니다.
- .tar 이름에 hardware 이름을 추가합니다. 이에 따라, `-amd64.tar` 또는 `-arm64.tar` 파일이 만들어 집니다.
- local macbook 에서 setup.v2.sh 가 OFFLINE_DIR 의 이미지를 로딩하는데 성공합니다.
```
jk@Jk-Kim-VVVY6C7KYV offline % ls -al
total 20225488
drwxr-xr-x  17 jk  staff         544 Aug 28 14:20 .
drwxr-xr-x   8 jk  staff         256 …
```

setup.v2.sh - OFFLINE_DIR 에서 .tar 이미지를 설치합니다.

---

aws/scripts/setup.v2.sh
aws/verify-install/rhel-8-offline.pkr.hcl
aws/verify-install/rhel-9.pkr.hcl
compose/local-image-prune.sh

- `install::load_image_from_tarball_in_offline`의 버그를 수정합니다.
- hardware 값이 `x86_64` 인 경우, `amd64` 로 값을 대체합니다.
- hardware 값이 `aarch64` 인 경우, `arm64` 로 값을 대체합니다.
- container platform 은 `linux/amd64`, `linux/arm64` 로 구분됩니다.
- docker-compose 실행파일은 `x86_64`,  `aarch64` 로 구분됩니다.
- `$(uname -m | tr '[:upper:]' '[:lower:]')`의 값은 리눅스의 경우 `x86_64`, `aarch64`, macOS 의 경우 `arm64`로 구분됩니다.
아래 4개 명령이 모두 기대한대로 작동합니다.
- `./verify-install.sh 11.1.1 rhel-8-offline x86_64 podman`
- `./verify-install.sh 11.1.1 rhel-8-offline x86_64 docker`
- `./verify-install.sh 11.1.1 rhel-8-offline arm64 podman`
- `./verify-install.sh 11.1.1 rhel-8-offline arm64 docker`

setup.v2.sh: OFFLINE_DIR 설치 버그 수정

---

aws/scripts/setup.v2.sh
aws/verify-install/amazon-linux-2023.pkr.hcl
aws/verify-install/centos-9.pkr.hcl
aws/verify-install/rhel-10.pkr.hcl
aws/verify-install/rhel-8-offline.pkr.hcl
aws/verify-install/rhel-8.pkr.hcl
aws/verify-install/rhel-9.pkr.hcl
aws/verify-install/rocky-8.pkr.hcl
aws/verify-install/ubuntu-22.04.pkr.hcl
aws/verify-install/ubuntu-24.04.pkr.hcl

- `setup.v2.sh --install-compose-package <version>` 옵션을 구현합니다.
- 이 기능은 기존 `setup.sh`와 동등한 설치 기능으로, container engine 설치, compose package 설치까지만 수행합니다.
- .env 자동 설정, container 실행, migration 실행 등을 수행하지 않습니다.
- .env 파일이 symbolic link 인 경우, 이를 삭제하고, .env.template 또는 compose-env 를 .env 로 복사합니다.
- 설치 도중 실패한 경우, 문제를 해결하고, 다시 재설치하는 경우, mysql db password 등이 변경되지 않도록, .env 를 그대로 유지합니다.
- .env 파일이 일반 파일로 이미 존재하는 경우, 이를 덮어쓰지 않고, 그대로 활용합니다. 같은 버전으로 두번 설치하는 것을 허용합니다.
```
jk@Jk-Kim-VVVY6C7KYV ~ % ./setup.v2.sh --install-compose-package 
ERROR: Version is required. Please provide a version.
setup.v2.sh 25.08.8, the QueryPie installation script.
Usage: setup.v2.sh [options]
or setup.v2.sh [options] --install <version>
or setup.v2.sh [options] --install-container-engine
or setup.v2.sh [options] …
```

setup.v2.sh: setup.sh 호환기능을 구현합니다.

---

aws/ec2
tencent-cloud/cvm

- /aws/ec2 스크립트를 활용하여, 동일한 기능을 제공하는 스크립트를 /tencent-cloud/cvm 으로 작성합니다.
- start, stop, terminate 기능을 검증하였습니다.
```
% ./cvm
Tencent Cloud CVM Instance Management Script v25.08.3
Usage:
./cvm start     - Start all instances owned by jk
./cvm stop      - Stop all instances owned by jk
./cvm terminate - Terminate instances owned by jk (per-instance confirmation)
./cvm status    - List instances owned by jk
./cvm help      - Show this help message
Note: This script automatically finds and manages all CVM instances
tagged with Owner=jk (case-insensitive matching)
```

Tencent: cvm - VM Stop, Start, Terminate 하는 도구
