merge-env/merge-env.sh
REDIS_NODES 를 이전버전 환경변수 HOST, PORT 로 생성하던 조건 변경 (MODE -> NODES 체크로 변경)
MODE 가 사라짐을 대비한 수정
Test
1. MODE, NODES 존재
1. HOST, PORT -> MODE(STANDARD), NODES(HOST:PORT) 변경 O
2. MODE, NODES -> MODE, NODES merge O  
2. NODES 만 존재
1. HOST, PORT -> NODES(HOST:PORT) 변경 O
2. MODE, NODES -> NODES merge O   (MODE는 delete)
첨언) cursor 가 작성한 내용을 junie 가 수정함. (필요없는 스페이스 삭제등)
=> REDIS_NODES 를 이전버전 환경변수 HOST, PORT 로 생성하던 조건 변경 (MODE -> NODES 체크로 변경)

merge-env/merge-env.sh
mac 과 linux 에서 sed 명령어 다름으로 인한 redis 항목 중복 출력 수정 & dry run 시에 중복 출력 수정
=> mac 과 linux 에서 sed 결과 다름으로 인한 redis 항목 중복 출력 수정

terraform-install/modules/ec2/main.tf, terraform-install/querypie/compose-env.tpl, terraform-install/querypie/readme.md, terraform-install/querypie/userdata-script.tpl
1. AWS_ACCOUNT_ID를 현재 실행 계정 ID로 자동 설정 기능 추가
2. 스크립트 실행 시 미설정 변수 검증을 위한 set -o nounset 옵션 적용
3. 쿼리파이 권장 EC2 인스턴스 타입을 m6i.xlarge로 변경
=> AWS 계정 ID 자동 설정 및 스크립트 안정성 개선

cs-reporter/README.md, cs-reporter/conn_checker.ps1, cs-reporter/conn_checker.sh
- 20회 동안 지정된 IP 의 9000번 포트로 접속 테스트를 수행하는 스크립트를 추가합니다.
=> Add Connection Checker

api/workflow/config.py, api/workflow/readme.md, api/workflow/workflow.py
- SQL Request Workflow 상신, Rule 기반 자동 승인, 실행 기능
- 다단계 승인 프로세스 자동화
- API 사용 예제 제공
=> feat: API를 이용한 SQL Request 워크플로우 자동화 예제

beta/EnvCheck.sh, beta/README.md
=> 출력 파일에 컬러값 제외 및 README 에 추가

aws-ami/README.md, aws-ami/build-ami.sh, aws-ami/querypie-ami.pkr.hcl
- HashiCorp Packer 를 이용하여, AMI 빌드를 자동화합니다.
- HCL2 스크립트로 AMI 빌드 명세를 코드로 구현합니다.
- 구현된 상태
- `build-ami.sh` 스크립트를 실행하면, `packer` 명령이 실행됩니다.
- Amazon Linux 2023 을 Source AMI 로 사용합니다.
- 빌드용 SSH KeyPair 생성, EC2 Instance 생성, Security Group 생성 등 과정이 자동으로 진행됩니다.
- AMI 빌드 과정 자체는, linux package 설치 과정에서 충돌이 발생하여 실패합니다.
- `packer`는 빌드 과정에서 생성한 임시 자원을 모두 정리하고, 종료합니다.
- 실행결과
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % ./build-ami.sh 10.3.0
+ packer build -var querypie_version=10.3.0 -var ami_name_prefix=querypie-suite querypie-ami.pkr.hcl
build-querypie-ami.amazon-ebs.amazon-linux-2023: output will be in this color.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating any provided VPC information
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating AMI Name: …
```
=> AMI 빌드 - querypie-ami.pkr.hcl 도입

aws-ami/README.md, aws-ami/querypie-ami.pkr.hcl
- `./build-ami.sh <version>`을 실행하면, AMI 이미지가 생성됩니다.
- 사용되지 않는 launch_block_device_mappings 를 삭제합니다.
- README.md 의 "Build an AMI" 섹션을 업데이트합니다.
```
jk@Jk-Kim-QL44T41DXQ aws-ami % ./build-ami.sh 10.3.0
+ packer build -var querypie_version=10.3.0 -var ami_name_prefix=querypie-suite querypie-ami.pkr.hcl
build-querypie-ami.amazon-ebs.amazon-linux-2023: output will be in this color.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating any provided VPC information
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating AMI Name: querypie-suite-10.3.0-20250606085507
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Found Image ID: ami-0c12d48b7c30e8d8e
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Creating temporary keypair: …
```
=> AMI 빌드 - 기본 패키지 설치과정 구현

aws-ami/querypie-ami.pkr.hcl, aws-ami/scripts/init-compose-env.sh
- `setup.sh`를 활용하여, QueryPie Package 를 설치합니다.
- `init-compose-env.sh`가 `compose-env` 파일의 DB_PASSWORD 등을 자동으로 채우도록 구현합니다.
- TODO: Harbor 계정 설정, Docker Image 내려받기, Docker Container 실행하기
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % ./build-ami.sh 10.3.0
+ packer build -var querypie_version=10.3.0 -var ami_name_prefix=querypie-suite querypie-ami.pkr.hcl
build-querypie-ami.amazon-ebs.amazon-linux-2023: output will be in this color.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating any provided VPC information
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating AMI Name: querypie-suite-10.3.0-20250611110126
(생략)
==> build-querypie-ami.amazon-ebs.amazon-linux-2023:
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Complete!
==> …
```
=> AMI 빌드 - QueryPie Package 를 설치합니다.

aws-ami/build-ami.sh, aws-ami/querypie-ami.pkr.hcl, aws-ami/scripts/tools-readyz
- AMI 빌드 과정에서, 더 많은 단계를 구현합니다.
- 각 container 를 순서에 따라 docker-pull 실행하고, Container 를 실행하도록, 단계를 구분합니다.
- Tools 실행 후, migrate.sh 를 실행하는 과정을 구현합니다.
- App Container 를 생성하고, 실행하지 않은 상태를 유지합니다. 이는, AMI 이미지 기반의 EC2 Instance 를 실행하였을 때, Container 가 자동으로 실행되는 상태입니다.
- `PACKER_OPTION` 환경변수를 도입합니다.
- `packer` 명령을 실행할 때, 추가적인 실행옵션을 받을 수 있습니다. 디버깅을 위해, 오류가 발생한 때, VM 을 삭제하지 않고, 실행을 중단하는 옵션을 지정할 수 있습니다.
- `PACKER_OPTION=-on-error=abort ./build-ami.sh 10.3.1`
AMI 이미지를 성공적으로 빌드하였습니다. 다만, 전체 빌드에 15분 이상 꽤 오랜 시간이 소요됩니다.
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % PACKER_OPTION=-on-error=abort ./build-ami.sh 10.3.1
PACKER_OPTION: -on-error=abort
+ packer build -var querypie_version=10.3.1 -var ami_name_prefix=querypie-suite -on-error=abort querypie-ami.pkr.hcl
build-querypie-ami.amazon-ebs.amazon-linux-2023: output …
```
=> AMI 빌드 - Tools 실행 후, migrate.sh 를 실행합니다.

aws-ami/scripts/setup.v2.sh
- setup.v2.sh 에 `scripts/init-compose-env` 스크립트의 기능을 포함합니다.
- `setup.v2.sh --populate-env <compose-env-file>`
- 지정한 compose-env 파일의 환경변수값을 자동으로 채워 넣습니다. PoC용 단일 서버 구성을 기준으로 설정값을 채웁니다.
- `setup.v2.sh --reset-credential <compose-env-file>`
- 지정한 compose-env 파일의 환경변수 가운데, PASSWORD, CREDENTIAL 유형의 값을 초기화, 삭제합니다.
- 위의 두 기능은, AMI 빌드에 사용됩니다.
- 사용법
```
Usage: setup.v2.sh [options] <version>
or setup.v2.sh [options] --install <version>
or setup.v2.sh [options] --install-partially-for-ami <version>
or setup.v2.sh [options] --upgrade <version>
or setup.v2.sh [options] --resume
or setup.v2.sh [options] --populate-env <compose-env-file>
or setup.v2.sh [options] --reset-credential <compose-env-file>
or setup.v2.sh [options] --help
OPTIONS:
-x, --xtrace        Print commands and their arguments as they …
```
=> AMI 빌드 - setup.v2.sh --populate-env, --reset-credential 구현

aws-ami/ami-build.pkr.hcl, aws-ami/querypie-first-boot.service, aws-ami/scripts/setup.v2.sh
- AMI 를 생성할 때, QueryPie 설치 과정을 일부만 수행하고, EC2 VM 생성 이후, 남은 설치 과정을 진행합니다.
- AMI 생성시 수행되는 과정
- compose-env 파일의 값을 채우기
- docker image 내려받기
- compose-env 파일의 credential 을 지우기
- EC2 생성 후 수행되는 과정
- compose-env 파일의 credential 생성하기
- tools migrate.sh 실행하기
- app container 실행하기
- querypie-first-boot.service 의 변경사항
- StartTimeout 을 600초로 길게 설정합니다. 처음 부팅 과정에서, migrate.sh 실행 완료까지 약 100초 소요되고, App Container 를 생성한 이후, querypie-first-boot.service 는 서비스 실행 성공으로 간주합니다.
-  QueryPie App Container 의 실행이 완료되는데 약 3분, 180초 가량 더 소요됩니다.
- AMI 생성에 성공합니다.
- EC2 VM 생성 후, 자동 검증에 성공합니다.
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % ./ami-build.sh 10.3.4
...
2025-07-04T18:42:11+09:00: Build 'build-querypie-ami.amazon-ebs.amazon-linux-2023' finished after 6 minutes 5 seconds.
<생략>
==> Wait completed after 6 minutes 5 seconds
==> …
```
=> AMI 빌드 - setup.v2.sh --resume 을 VM 생성 이후에 실행

aws-ami/scripts/setup.v2.sh
- `setup.v2.sh --upgrade <version>` 으로 제품을 업그레이드하는 기능을 구현합니다.
- 기존 실행 중인 버전을 확인하고, 업그레이드할 버전이 더 높은 버전인 경우, 업그레이드를 수행합니다.
- 기존 compose-env 파일의 환경변수 설정값을 업그레이드할 compose-env 에 자동으로 옮깁니다.
- querypie/current 라는 symlink 를 만들고, 현재 실행 중인 버전의 디렉토리를 가리킵니다.
- 아직, 예외처리 등 고려할 요소가 몇가지 남아 있습니다.
- 기존 compose-env 파일에 추가로 정의한 환경변수의 값은 자동으로 옮겨지지 않습니다. 수작업으로 옮기는 것을 가이드하거나, setup.v2.sh 의 기능을 개선해야 합니다.
- 10.3.0 에서 11.0.0 으로 업그레이드가 잘 진행됩니다.
```
[ec2-user@ip-172-31-11-201 ~]$ setup.v2.sh --upgrade 11.0.0 
+ docker exec querypie-app-1 readyz wait
#
#
+ curl -fsSL https://dl.querypie.com/releases/compose/11.0.x/package.tar.gz -o package.tar.gz
+ tar zxvf package.tar.gz -C ./querypie/11.0.0
./
./novac-compose.yml
./nginx.d/
./nginx.d/ssl.conf
./nginx.d/.gitkeep
./certs/
./certs/.gitkeep
./compose-env …
```
=> AMI 빌드 - setup.v2.sh --upgrade 구현

aws-ami/scripts/setup.v2.sh
- MySQL 의 데이터 디렉토리 경로를 `./mysql` 이 아닌, `../mysql` 을 사용합니다.
- 이를 통해, mysql, redis container 를 업그레이드된 버전의 docker-compose.yml 에서 실행/종료할 수 있게 변경합니다.
- 이러한 설정 변경은, 구 버전 패키지 디렉토리에 대한 의존성을 없애어 줍니다. 신 버전 패키지 디렉토리만 남기고, 과거의 디렉토리를 삭제할 수 있습니다. 계속 유지되어야 하는 데이터 디렉토리는 `./querypie/` 하위에 직접 두도록 합니다.
- Docker Registry 를 harbor.chequer.io 에서 docker hub 로 변경합니다.
- docker-compose.yml 안의 Repository 이름을 설치 시점에 변경합니다.
- 업그레이드 테스트를 위해, 10.2.x 버전의 QueryPie 를 설치할 수 있도록, 개선합니다.
- CABINET_DATA_DIR 경로를 `/data` 대신 `../data` 로 설정하고, 해당 디렉토리를 생성해 둡니다.
- REDIS_CONNECTION_MODE, QUERYPIE_WEB_URL, AWS_ACCOUNT_ID 를 적절히 설정합니다.
- Upgrade 과정에서 새 버전을 compose-env 에 기록하지 않고, 기존 버전을 compose-env 에 기록합니다. 다음 PR 에서 개선할 예정입니다.
설치, 업그레이드를 성공합니다.
```
[ec2-user@ip-172-31-11-201 ~]$ setup.v2.sh 10.2.12
<생략>
[ec2-user@ip-172-31-11-201 ~]$ …
```
=> AMI 빌드 - setup.v2.sh --install 개선하기

aws-ami/ami-build.pkr.hcl, aws-ami/scripts/remove-ecs.sh
- Amazon Linux 2023 에는 ECS Optimized 설정이 적용되어, ECS Workload 로 운영할 수 있는 기능이 기본 탑재되어 있습니다.
- AMI 빌드시, 이 ECS Agent 기능을 종료하고 삭제합니다.
- 기대한 대로, 정상 작동합니다. AMI 빌드를 성공합니다.
```
jk@Jk-Kim-VVVY6C7KYV aws-ami % ./ami-build.sh 10.3.4
<생략>
2025-07-08T12:48:37+09:00: Provisioning with shell script: scripts/remove-ecs.sh
2025-07-08T12:48:37+09:00: + main
2025-07-08T12:48:37+09:00: + disable_ecs_agent_service
2025-07-08T12:48:37+09:00: + sudo systemctl stop ecs
2025-07-08T12:48:37+09:00: + sudo systemctl disable ecs
2025-07-08T12:48:37+09:00: Removed "/etc/systemd/system/multi-user.target.wants/ecs.service".
2025-07-08T12:48:38+09:00: + docker_system_prune
2025-07-08T12:48:38+09:00: + docker stop ecs-agent
2025-07-08T12:48:38+09:00: ecs-agent
2025-07-08T12:48:38+09:00: + docker rm ecs-agent …
```
=> AMI 빌드 - AMI 빌드 과정에서 ECS 기능 종료 및 제거

beta/QueryPie.sh
parameter validation 조건문을 if -> case 로 변경
=> parameter validation 조건문을 if -> case 로 변경

aws-ami/scripts/setup.v2.sh
- application log directory 를 /var/log/querypie 에서 ./querypie/log 로 변경합니다.
- root 권한을 요구하는 설치 과정을 최소로 줄입니다.
- setup.v2.sh 자체의 version 을 스크립트 내에 기록합니다. `setup.v2.sh --version` 또는 `setup.v2.sh -V` 로 확인합니다.
- version 은 YY.MM.PATCH 형식으로 지정합니다. 처음 버전은 25.07.0 입니다.
- 성공
=> AMI 빌드 - log 디렉토리 경로 변경, setup.v2.sh 자체 버전 추가

aws-ami/scripts/setup.v2.sh
- setup.v2.sh 를 아무 인자 없이 실행하면, 자동 설치/업그레이드 모드가 실행됩니다.
- 기존 설치 현황을 살펴보고, 신규 설치를 수행할 것인지, 업그레이드를 수행할 것인지, 판단합니다.
- 이용자에게 설치, 업그레이드 여부를 물어보고, 동의를 받아 설치를 수행합니다.
- 이미 최신 버전이 설치된 경우에는, 설치/업그레이드를 수행하지 않습니다.
- `install::ask_yes` 함수를 구현합니다.
- stdin 이 tty 인 경우에는, 이용자에게 동의를 구합니다.
- stdin 이 tty 가 아닌 경우, 이용자가 거부하였다고 간주합니다.
- `--yes` 옵션이 주어진 경우, tty 여부와 무관하게, 항상 동의한다고 간주합니다.
- 현재 QueryPie 최신 버전은 11.0.0 입니다. SCRIPT_VERSION 은 25.07.1 로 업데이트합니다.
- `bash <(curl -s https://url/setup.v2.sh)` 방식으로 명령을 실행할 수 있습니다. 이용자로부터 입력값을 받는 경우, `curl -s https://url/setup.v2.sh | bash` 방식으로 실행하지 못합니다.
```
[ec2-user@ip-172-31-11-201 ~]$ bash <(curl -s https://raw.githubusercontent.com/querypie/tpm/refs/heads/jk/ami-first-boot-a/aws-ami/scripts/setup.v2.sh)
Do you want to upgrade QueryPie from 10.2.12 to 11.0.0?
Do you …
```
=> AMI 빌드 - setup.v2.sh 자동 설치 기능

aws-ami/scripts/setup.v2.sh
- `###`, `##`, `#` prefix 와 함께 출력되는 로깅 메시지의 영어 표현을 개선합니다.
- Junie Pro 를 이용하여, 영어 표현을 리뷰하고 개선합니다.
- 잘 작동합니다.
=> AMI 빌드 - setup.v2.sh 로깅 메시지 개선

podman/README.md, podman/database-compose.yml, podman/tools-compose.yml
- tools-compose.yml 을 작성합니다.
- .env 에 기본으로 제공되는 환경변수만으로 podman-compose 에서 작동할 수 있도록 환경변수를 정의합니다. tools 가 지원하는 meta, snapshot, log db 별 설정 기능은 별도 문서를 통해 가이드합니다.
- 추후, tools 가 환경변수 기본값 설정 기능을 container 내부에 갖게 되면, .env 파일에 환경변수를 추가하는 것으로, 간단하게 문제가 해결될 수 있습니다.
- name 을 querypie 로 사용하지 않고, 각 compose.yml 파일에서 별도의 name 을 사용합니다. 그렇지 않으면, 다른 container, network 를 orphaned 로 간주하여, 종료/삭제하려는 시도를 하며, 경고/에러가 발생합니다.
- podman-compose 는 ${VARIABLE1:-${VARIABLE2}} 와 같은 interpolation 기능을 지원하지 않습니다.
- https://github.com/containers/podman-compose/blob/main/podman_compose.py#L241
- podman-compose 가 지원하는 interpolation 기능의 범위는 위의 코드에서 확인할 수 있으며, 다음과 같습니다.
```
```
migration 이 작동하는 것을 확인합니다. docker-compose, podman-compose 모두 성공합니다.
```
[ec2-user@ip-172-31-11-201 podman]$ docker-compose -f database-compose.yml up -d …
```
=> Podman: QueryPie Tools 를 위한 tools-compose.yml 준비

podman/querypie-compose.yml
- 기존 11.0.x/docker-compose.yml 에서 --profile querypie 에 해당하는 부분만 옮겨옵니다.
- 아직, 기능이 작동하지 않습니다. 이후, PR 에서 변경사항을 추적할 수 있습니다.
=> podman: querypie-compose.yml 처음 만들기

aws-ami/scripts/setup.v2.sh
이 PR은 QueryPie 설치 스크립트(setup.v2.sh)에 Podman 지원을 추가하고, 환경 설정 파일 관리를 개선하여 더욱 유연하고 안정적인 설치 환경을 제공합니다.
1. Podman 지원 추가
- Docker와 Podman을 자동으로 감지하여 적절한 명령어 선택
- docker/podman 및 docker-compose/podman-compose 자동 전환
- Podman 환경에서도 원활한 QueryPie 설치 및 운영 가능
2. 환경 설정 파일 개선
- compose-env → .env 파일로 통일
- .env.template 지원 추가로 더 유연한 환경 설정
- 기존 compose-env 파일과의 호환성 유지
3. SELinux 보안 설정 검증 추가
- SELinux가 활성화된 환경에서 컨테이너 파일 컨텍스트 자동 검증
- 필요한 경우 container_file_t 컨텍스트로 자동 변경
- 보안 정책 준수로 인한 컨테이너 오류 방지
4. 설치 프로세스 개선
- `--universal` 옵션 추가로 범용 패키지 지원
- 비대화형 환경에서 `--quiet` 옵션 자동 적용
- 더 안정적인 컨테이너 상태 검증
5. 코드 품질 향상
- 변수 기반 명령어 사용으로 유지보수성 향상
- 오류 처리 및 로깅 개선
- 코드 중복 제거 및 구조 개선
- 호환성: 기존 Docker 환경에서의 동작에 영향 없음
- 자동 감지: 시스템에 설치된 컨테이너 엔진을 자동으로 감지
- 백워드 호환: 기존 설치 환경과 완전 호환
- 보안 강화: SELinux 정책 준수로 보안성 향상
[x] Docker 환경에서 정상 설치 …
=> setup.v2.sh: Podman 지원 및 환경 설정 개선

compose/universal/README.ja.md, compose/universal/README.ko.md, compose/universal/README.md
- MySQL volume 생성에 대한 설명은 적용을 취소하였기에 삭제합니다.
- setup.v2.sh 사용법을 문서의 앞부분에 추가합니다.
=> universal: README.md 등 문서 업데이트

aws-ami/scripts/setup.v2.sh, compose/local-archive.sh
- setup.v2.sh 에서 docker, podman 설치 여부 검사하는 기능의 버그 수정
- podman 설치 여부를 검사하도록 추가
- SCRIPT_VERSION="25.07.10"
- local-archive.sh 의 버그 수정
=> setup.v2.sh: 버그수정 - Podman 설치 여부 확인하기

aws-ami/scripts/setup.v2.sh
- SCRIPT_VERSION="25.07.11"
- #71 에서 누락된 것을 추가합니다.
=> setup.v2.sh: Ask yes for unexpected version format

aws-ami/scripts/setup.v2.sh
- dl.querypie.com 에서 설치하는 docker-compose 의 파일위치를 변경합니다.
- 기존: `https://dl.querypie.com/releases/bin/docker-compose-$(uname -s)-$(uname -m)`
- 변경: `https://dl.querypie.com/releases/bin/v2.39.1/docker-compose-${kernel}-${hardware}`
- macos 에서 인식하는 hardware platform 이 arm64 인 경우, aarch64 로 값을 바꿉니다.
- install::docker_compose 를 리팩토링합니다.
- 설치된, 또는 설치한 docker-compose 버전을 보여줍니다.
- 로깅 메시지를 개선합니다.
- macbook 에서 설치에 성공합니다. `./setup.v2.sh --install 11.0.1-beta`
- macbook 에서 Docker Desktop 패키지 중 일부인 /usr/local/bin/docker-compose 를 삭제하고, 설치에 성공합니다. https://dl.querypie.com/releases/bin/v2.39.1/docker-compose-darwin-aarch64 를 설치하고, 정상 작동합니다.
- Packer 스크립트, `./ubuntu24.04-install.sh 11.0.1` 를 성공합니다.
- Packer 스크립트, `./az2023-install.sh 11.0.1` 를 성공합니다.
=> setup.v2.sh: docker-compose 파일 위치 변경

aws/scripts/setup.v2.sh, aws/verify-upgrade-uninstall/amazon-linux-2023.pkr.hcl, aws/verify-upgrade-uninstall/ubuntu-22.04.pkr.hcl, aws/verify-upgrade-uninstall/ubuntu-24.04.pkr.hcl, aws/verify-upgrade-uninstall/verify-upgrade-uninstall.sh, compose/local-archive.sh
- setup.v2.sh: SCRIPT_VERSION="25.08.3"
- setup.v2.sh --verify-not-installed 를 구현합니다.
- querypie/current, querypie/mysql 이 존재하지 않는다는 것을 검증합니다.
- container 들이 존재하지 않는다는 것을 검증합니다.
- aws/verify-upgrade-uninstall/ 에서 upgrade, uninstall 검증을 자동화합니다.
- verify-upgrade-uninstall.sh 스크립트를 구현합니다. 처음 설치할 버전, 업그레이드할 버전을 입력받아, 설치, 업그레이드, 삭제를 순차적으로 수행하고 검증합니다.
- packer script 로 설치, 업그레이드, 삭제를 자동으로 수행하고 검증합니다.
```
% ./verify-upgrade-uninstall.sh
Usage: ./verify-upgrade-uninstall.sh <initial_version> <upgrade_version> [<distro>] [<architecture>]
EXAMPLE:
./verify-upgrade-uninstall.sh 11.0.1 11.1.1 amazon-linux-2023
./verify-upgrade-uninstall.sh 11.0.1 11.1.1 amazon-linux-2023 arm64
./verify-upgrade-uninstall.sh 11.0.1 11.1.1 ubuntu-24.04
./verify-upgrade-uninstall.sh 11.0.1 11.1.1 ubuntu-22.04 …
```
=> AWS: upgrade, uninstall 검증을 자동화

aws/scripts/setup.v2.sh
- SCRIPT_VERSION="25.08.7"
- 폐쇄망 환경, Closed Network 에서 setup.v2.sh 를 이용해 제품을 설치할 수 있도록, 기능을 개선합니다.
- Compose Package 를 universal/package.tar.gz 으로 기본 선택합니다.
- RHEL 계열의 배포본에서는 Docker 대신 Podman 을 기본 Container Engine 으로 사용합니다. 이에 따라, universal package 를 기본으로 선택합니다.
- 이에 따라, `--universal` 옵션을 Deprecated 합니다. 호환성을 위해 기능을 유지합니다.
- `package.tar.gz` 을 dl.querypie.com 에서 직접 내려받지 못하는 경우, 현재 디렉토리에 두고 사용할 수 있습니다.
- 현재 디렉토리에서 `package.tar.gz`을 발견한 경우, 이것을 설치에 사용합니다. 또한, 이 파일을 자동으로 삭제하지 않습니다.
- dl.querypie.com 에서 `package.tar.gz`을 직접 내려받은 경우에는, 설치 후, 이 파일을 삭제합니다.
- DOCKER_REGISTRY 환경변수를 참조합니다.
- 기본값은 `docker.io/querypie/`입니다. 이 환경변수를 이용하여, Private Docker Registry 의 이미지를 설치할 수 있습니다.
- 사내 맥북에서는, `DOCKER_REGISTRY=harbor.chequer.io/querypie/ ./setup.v2.sh --install 11.1.2` 이 명령으로 docker registry 를 바꾸어, 설치 …
=> setup.v2.sh: Closed Network 설치를 위한 기능 개선

querypie-monitoring/monitoring.sh
=> grafana 12.1.1 로 업그레이드
